# Generated by Django 4.2.7 on 2023-11-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("From", models.CharField(max_length=200)),
                ("To", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="media")),
                ("Deperature", models.IntegerField()),
                ("Return", models.IntegerField()),
                ("Bookingclass", models.CharField(max_length=100)),
                ("Traveler", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
