# Generated by Django 4.2.7 on 2023-11-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name="airway",
            old_name="Deperature",
            new_name="Deperature_date",
        ),
    ]
